application :
  port : 8000
  base_url : "http://127.0.0.1:8000"
  hmac_secret : "my-secret-key"
  redis_uri: "redis://127.0.0.1:6379"
database: 
  port : 8080
  host : "127.0.0.1"
  username : "postgres"
  password : "p@ssw0rd"
  database_name : "newsletter"
email_client:
  base_url : "https://api.brevo.com/v3/smtp"
  sender_email : "pody6163@gmail.com"
  sender_name : "Abdulrahman Sender"
  authorization_token : "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"
  timeout_milliseconds : 1000
